/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IntentFiCCIP, IntentFiCCIPInterface } from "../IntentFiCCIP";

const _abi = [
  {
    type: "function",
    name: "ccipSend",
    inputs: [
      {
        name: "destinationChainSelector",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "message",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "messageId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getFee",
    inputs: [
      {
        name: "destinationChainSelector",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "message",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "fee",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IntentFiCCIP__factory {
  static readonly abi = _abi;
  static createInterface(): IntentFiCCIPInterface {
    return new Interface(_abi) as IntentFiCCIPInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IntentFiCCIP {
    return new Contract(address, _abi, runner) as unknown as IntentFiCCIP;
  }
}
