#!/usr/bin/env python3
"""
Script to carefully translate French comments and logs to English
while preserving Python keywords and syntax
"""

import re

def harmonize_file(filepath):
    """Harmonize French comments and logs to English in the file"""
    
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Dictionary of specific French to English translations
    # Only translate comments and string literals, not Python keywords
    translations = {
        # Comments
        "# Import du protocole de chat officiel Fetch.ai": "# Import official Fetch.ai chat protocol",
        "# Configuration du logging": "# Logging configuration", 
        "# Modèles compatibles ASI ONE et protocole Fetch.ai": "# Models compatible with ASI ONE and Fetch.ai protocol",
        "# Modèles de chat compatibles avec ASI1.ai": "# Chat models compatible with ASI1.ai",
        "# Définitions custom si le protocole officiel n'est pas disponible": "# Custom definitions if official protocol is not available",
        "# Modèles legacy pour compatibilité avec ton code existant": "# Legacy models for compatibility with existing code",
        "articles: list[dict[str, Any]]  # Articles avec review et rate ajoutés": "articles: list[dict[str, Any]]  # Articles with review and rate added",
        "# Modèles pour la communication avec Simon (Trading Agent)": "# Models for communication with Simon (Trading Agent)",
        "# Configuration de l'agent avec endpoint": "# Agent configuration with endpoint",
        "endpoint=[\"localhost:8001/submit\"],  # Endpoint local pour les tests": "endpoint=[\"localhost:8001/submit\"],  # Local endpoint for testing",
        "# Tokens autorisés pour les recommandations de trading": "# Authorized tokens for trading recommendations",
        "# Fichier des actualités généré par news.py": "# News file generated by news.py",
        "# Protocol pour IntentFi": "# Protocol for IntentFi",
        "# Protocol pour la communication avec Simon": "# Protocol for communication with Simon",
        "# Protocole de chat compatible ASI1.ai": "# Chat protocol compatible with ASI1.ai",
        "# Utilise le protocole officiel Fetch.ai": "# Use official Fetch.ai protocol",
        "# Fallback sur un protocole custom": "# Fallback to custom protocol",
        "# Configuration spécifique ASI ONE": "# ASI ONE specific configuration",
        "# Métadonnées pour ASI ONE": "# Metadata for ASI ONE",
        "# Données d'enregistrement pour ASI ONE": "# Registration data for ASI ONE",
        
        # Log messages and strings
        "✅ Protocole de chat officiel Fetch.ai chargé": "✅ Official Fetch.ai chat protocol loaded",
        "⚠️ Protocole de chat officiel non disponible, utilisation du protocole custom": "⚠️ Official chat protocol not available, using custom protocol",
        
        # Function docstrings and comments (preserve function structure)
        '"""Traite les réponses structurées de Claude AI pour les recommandations d\'intents"""': '"""Processes Claude AI structured responses for intent recommendations"""',
        '"""Traite une demande d\'intent via chat"""': '"""Processes an intent request via chat"""',
        '"""Traite une demande d\'analyse trading via chat"""': '"""Processes a trading analysis request via chat"""',
        '"""Traite un message texte simple via chat"""': '"""Processes a simple text message via chat"""',
        '"""Extrait une demande d\'intent d\'un message texte"""': '"""Extracts an intent request from a text message"""',
        '"""Extrait une demande de trading d\'un message texte"""': '"""Extracts a trading request from a text message"""',
        '"""Envoie les commandes d\'aide via chat"""': '"""Sends help commands via chat"""',
        '"""Traite une conversation générale en utilisant Claude AI"""': '"""Processes general conversation using Claude AI"""',
        '"""Envoie un message d\'erreur via chat"""': '"""Sends an error message via chat"""',
        '"""Traite les demandes d\'intent et génère des recommandations"""': '"""Processes intent requests and generates recommendations"""',
        '"""Génère une recommandation d\'intent en contactant réellement l\'AI agent Claude"""': '"""Generates an intent recommendation by actually contacting Claude AI agent"""',
        '"""Endpoint de santé"""': '"""Health endpoint"""',
        '"""Endpoint pour demander une recommandation d\'intent"""': '"""Endpoint to request an intent recommendation"""',
        '"""Endpoint pour récupérer les intents populaires"""': '"""Endpoint to retrieve popular intents"""',
        '"""Endpoint pour récupérer le contenu du fichier news_logs.json"""': '"""Endpoint to retrieve news_logs.json file content"""',
        
        # Common French log phrases
        "🚀 IntentFi Agent démarré!": "🚀 IntentFi Agent started!",
        "📍 Endpoints disponibles:": "📍 Available endpoints:",
        "🔗 Protocoles activés:": "🔗 Activated protocols:",
        "🔗 INTÉGRATION ASI1.AI PRÊTE! 🔗": "🔗 ASI1.AI INTEGRATION READY! 🔗",
        "📨 Vous pouvez maintenant communiquer avec cet agent via:": "📨 You can now communicate with this agent via:",
        "🔍 Test de connectivité avec AI Agent:": "🔍 Connectivity test with AI Agent:",
        "📤 Message de test envoyé à l'AI Agent": "📤 Test message sent to AI Agent",
        "❌ Erreur lors de l'envoi du test:": "❌ Test sending error:",
        "💬 Test du protocole de chat officiel...": "💬 Official chat protocol test...",
        "✅ Protocole de chat officiel initialisé avec succès!": "✅ Official chat protocol initialized successfully!",
        "⚠️ Protocole de chat custom activé - installation de uagents_core recommandée": "⚠️ Custom chat protocol activated - uagents_core installation recommended",
        "📤 Test structuré envoyé à l'AI Agent": "📤 Structured test sent to AI Agent",
        "❌ Erreur lors de l'envoi du test structuré:": "❌ Structured test sending error:",
        "ℹ️ Le test structuré peut être désactivé pour éviter le rate limiting": "ℹ️ Structured test can be disabled to avoid rate limiting",
        "💬 Test du protocole de chat legacy pour compatibilité...": "💬acy chat protocol test for compatibility...",
        "✅ Protocole de chat legacy initialisé avec succès!": "✅ Legacy chat protocol initialized successfully!",
        
        # Error messages
        "Erreur lors de la génération:": "Error during generation:",
        "❌ Erreur JSON :": "❌ JSON Error:",
        "❌ Erreur lors de la lecture :": "❌ Reading error:",
        "❌ Erreur lors de l'inclusion du protocole de chat:": "❌ Error including chat protocol:",
        "❌ Erreur lors de l'envoi à Simon Agent:": "❌ Error sending to Simon Agent:",
        "❌ Erreur lors de l'analyse trading:": "❌ Trading analysis error:",
        
        # API related
        "🌐 API Call - Récupération du JSON des actualités": "🌐 API Call - Retrieving news JSON",
        "⚠️ Fichier {NEWS_FILE} non trouvé": "⚠️ File {NEWS_FILE} not found",
        "📰 JSON récupéré :": "📰 JSON retrieved:",
        "articles": "articles",  # Keep this as is
    }
    
    # Apply translations
    for french, english in translations.items():
        content = content.replace(french, english)
    
    # Additional regex-based translations for variable patterns
    # Translate specific patterns while preserving structure
    
    # Info log messages with variable content
    content = re.sub(
        r'ctx\.logger\.info\(f"🌐 API Call - Recommend Intent pour user: \{([^}]+)\}"\)',
        r'ctx.logger.info(f"🌐 API Call - Recommend Intent for user: {\1}")',
        content
    )
    
    # Warning messages with file paths
    content = re.sub(
        r'ctx\.logger\.warning\(f"⚠️ Fichier \{([^}]+)\} non trouvé"\)',
        r'ctx.logger.warning(f"⚠️ File {\1} not found")',
        content
    )
    
    # Info messages with counts
    content = re.sub(
        r'ctx\.logger\.info\(f"📰 JSON récupéré : \{([^}]+)\} articles"\)',
        r'ctx.logger.info(f"📰 JSON retrieved: {\1} articles")',
        content
    )
    
    return content

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) != 2:
        print("Usage: python harmonize_french_to_english.py <file_path>")
        sys.exit(1)
    
    filepath = sys.argv[1]
    
    try:
        harmonized_content = harmonize_file(filepath)
        
        # Write back to file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(harmonized_content)
        
        print(f"✅ Successfully harmonized {filepath}")
        
    except Exception as e:
        print(f"❌ Error harmonizing file: {e}")
        sys.exit(1)
