from typing import Any, Dict
from uagents import Agent, Context, Model, Protocol
from uagents.setup import fund_agent_if_low
import json
import uuid
from datetime import datetime, timezone
import os
import aiohttp
import statistics
import logging
import asyncio
import random
from enum import Enum
from uuid import uuid4

# Import official Fetch.ai chat protocol
try:
    from uagents_core.contrib.protocols.chat import (
        ChatMessage,
        ChatAcknowledgement, 
        TextContent,
        chat_protocol_spec
    )
    CHAT_PROTOCOL_AVAILABLE = True
    print("✅ Official Fetch.ai chat protocol loaded")
except ImportError:
    print("⚠️ Official chat protocol not available, using custom protocol")
    CHAT_PROTOCOL_AVAILABLE = False

# Logging configuration
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Models compatible with ASI ONE and Fetch.ai protocol
class MessageType(str, Enum):
    TEXT = "text"
    INTENT_REQUEST = "intent_request"
    TRADING_ANALYSIS = "trading_analysis"
    SYSTEM_STATUS = "system_status"
    ERROR = "error"

# Chat models compatible with ASI1.ai
if not CHAT_PROTOCOL_AVAILABLE:
    # Custom definitions if official protocol is not available
    class TextContent(Model):
        type: str = "text"
        text: str
    
    class ChatMessage(Model):
        timestamp: datetime
        msg_id: str
        content: list[TextContent]
    
    class ChatAcknowledgement(Model):
        timestamp: datetime
        acknowledged_msg_id: str
        metadata: dict[str, str] = None

# Legacy models for compatibility with existing code
class LegacyChatMessage(Model):
    message_id: str
    sender_id: str
    recipient_id: str
    message_type: MessageType
    content: str
    metadata: dict[str, Any] = {}
    timestamp: str

class ChatResponse(Model):
    message_id: str
    original_message_id: str
    sender_id: str
    recipient_id: str
    response_type: MessageType
    content: str
    metadata: dict[str, Any] = {}
    timestamp: str

class LegacyChatAcknowledgement(Model):
    message_id: str
    original_message_id: str
    sender_id: str
    status: str  # "received", "processed", "error"
    timestamp: str

class ConversationContext(Model):
    conversation_id: str
    participants: list[str]
    message_history: list[dict[str, Any]] = []
    context_data: dict[str, Any] = {}
    created_at: str
    last_activity: str


class TextPrompt(Model):
    text: str


class TextResponse(Model):
    text: str


class StructuredOutputPrompt(Model):
    prompt: str
    output_schema: dict[str, Any]


class StructuredOutputResponse(Model):
    output: dict[str, Any]


class IntentRequest(Model):
    user_id: str
    intent_type: str
    parameters: dict[str, Any]


class IntentResponse(Model):
    success: bool
    recommendation: dict[str, Any]
    message: str


class HealthResponse(Model):
    status: str
    agent: str
    address: str
    timestamp: str

class PopularIntentsResponse(Model):
    popular_intents: list[dict[str, Any]]
    total_count: int
    timestamp: str


class NewsJsonResponse(Model):
    articles: list[dict[str, Any]]
    total_articles: int
    timestamp: str
    status: str


class NewsJsonDetailsResponse(Model):
    articles: list[dict[str, Any]]  # Articles with review and rate added
    total_articles: int
    analyzed_articles: int
    timestamp: str
    status: str


# Models for communication with Simon (Trading Agent)
class TradingRecommendation(Model):
    token_symbol: str
    recommendation: str  # "buy", "sell", "hold"
    confidence: float  # 0.0 to 1.0
    reasoning: str
    price_target: float = None
    stop_loss: float = None
    news_sentiment: str  # "positive", "negative", "neutral"
    timestamp: str


class TradingAnalysisRequest(Model):
    token_symbol: str
    news_context: list[dict[str, Any]] = []
    request_id: str = ""
    timestamp: str = ""

class ASIOneMetadataResponse(Model):
    agent_address: str
    metadata: dict[str, Any]
    endpoints: dict[str, str]
    protocols: list[str]
    timestamp: str

class EmptyRequest(Model):
    """Modèle de requête vide pour les endpoints POST sans paramètres"""
    pass

class TradingAnalysisAPIResponse(Model):
    success: bool
    message: str
    analysis: dict[str, Any] = None
    timestamp: str


# Agent configuration with endpoint
agent = Agent(
    name="intellect",
    port=8001,
    seed="intentfi-agent-seed-phrase",
    endpoint=["localhost:8001/submit"],  # Local endpoint for testing
    mailbox=True,
)

print(f"Agent address: {agent.address}")
fund_agent_if_low(agent.wallet.address())

AI_AGENT_ADDRESS = "agent1qvk7q2av3e2y5gf5s90nfzkc8a48q3wdqeevwrtgqfdl0k78rspd6f2l4dx"
SIMON_AGENT_ADDRESS = "agent1q0q5rqwj7q4upgm7fwf4dmv675nl4nqgy9tgp3qgyn8wlxwz804pxuj7032"  # Simon Agent

# Authorized tokens for trading recommendations
ALLOWED_TOKENS = ["ARBITRUM", "ETH", "FLOW", "OPTI"]

# News file generated by news.py
NEWS_FILE = "news_logs.json"

# Protocol for IntentFi
intentfi_protocol = Protocol("IntentFi")

# Protocol for communication with Simon
simon_protocol = Protocol("IntellectCommunication")

# Chat protocol compatible with ASI1.ai
if CHAT_PROTOCOL_AVAILABLE:
    # Use official Fetch.ai protocol
    chat_protocol = Protocol(spec=chat_protocol_spec)
else:
    # Fallback to custom protocol
    chat_protocol = Protocol("ASI_ONE_Chat")

# ASI ONE specific configuration
ASI_ONE_REGISTRY_ADDRESS = "agent1qd3k2k9k3qx7q3x7q3x7q3x7q3x7q3x7q3x7q3x7q3x7q3x7"
ASI_ONE_CHAT_VERSION = "1.0.0"

# Metadata for ASI ONE
AGENT_METADATA = {
    "name": "IntentFi Agent",
    "version": "1.0.0", 
    "description": "Expert en recommandations d'intents financiers et analyse trading crypto",
    "capabilities": [
        "intent_generation",
        "trading_analysis",
        "market_sentiment", 
        "cross_chain_recommendations",
        "risk_management"
    ],
    "supported_tokens": ALLOWED_TOKENS + ["BTC", "USDC", "USDT", "SOL", "ADA", "MATIC", "AVAX", "DOT", "LINK", "UNI"],
    "languages": ["fr", "en"],
    "chat_protocol_version": ASI_ONE_CHAT_VERSION
}

@agent.on_event("startup")
async def register_with_asi_one_network(ctx: Context):
    """Enregistre l'agent dans le réseau ASI ONE"""
    try:
        ctx.logger.info("🔗 Enregistrement dans le réseau ASI ONE...")
        
        # Registration data for ASI ONE
        registration_payload = {
            "agent_address": ctx.agent.address,
            "name": "IntentFi Agent",
            "description": "Expert en recommandations d'intents financiers et analyse trading crypto",
            "version": "1.0.0",
            "capabilities": [
                "intent_generation",
                "trading_analysis", 
                "market_sentiment",
                "cross_chain_recommendations",
                "risk_management"
            ],
            "supported_protocols": ["ASI_ONE_Chat", "IntentFi"],
            "metadata_endpoint": "/asi-one/metadata",
            "chat_endpoint": "/chat/send",
            "health_endpoint": "/health"
        }
        
        ctx.logger.info("✅ Agent accessible publiquement via ngrok!")
        ctx.logger.info(f"🎯 Agent ID: {ctx.agent.address}")
        
    except Exception as e:
        ctx.logger.error(f"❌ Échec de l'enregistrement dans le réseau ASI ONE: {e}")
        raise e
# Endpoint de découverte pour ASI ONE
@agent.on_rest_get("/asi-one/metadata", ASIOneMetadataResponse)
async def get_asi_one_metadata(ctx: Context) -> ASIOneMetadataResponse:
    """Endpoint de métadonnées pour ASI ONE"""
    return ASIOneMetadataResponse(
        agent_address=ctx.agent.address,
        metadata=AGENT_METADATA,
        endpoints={
            "chat": "/chat/send",
            "history": "/chat/history/{conversation_id}",
            "conversations": "/chat/conversations",
            "analytics": "/chat/analytics",
            "trading": "/trading/recommend",
            "health": "/health",
            "getJson": "/getJson",
            "getJsonDetails": "/getJsonDetails",
            "getAnalyzed": "/getAnalyzed",
            "updateAnalyzed": "/updateAnalyzed"
        },
        protocols=["ASI_ONE_Chat", "IntentFi", "IntelleC Communication"],
        timestamp=datetime.now().isoformat()
    )

# Variables pour gérer les conversations actives
active_conversations = {}
conversation_history = {}

# Handler supprimé - incompatible avec protocole verrouillé

async def process_chat_text(ctx: Context, text: str, sender: str) -> str:
    """Traite un message texte et génère une réponse appropriée"""
    try:
        text_lower = text.lower()
        
        # Détection d'intents dans le message
        if any(word in text_lower for word in ["intent", "recommand", "stratégie", "conseil"]):
            return await generate_intent_response_text(ctx, text, sender)
        elif any(word in text_lower for word in ["trading", "trade", "acheter", "vendre", "buy", "sell", "eth", "btc"]):
            return await generate_trading_response_text(ctx, text, sender)
        elif any(word in text_lower for word in ["aide", "help", "commands", "commandes"]):
            return get_help_text()
        else:
            return f"Bonjour ! Je suis IntentFi Agent, votre assistant pour les stratégies crypto et les intents financiers. Votre message: '{text}'. Comment puis-je vous aider avec vos investissements ?"
            
    except Exception as e:
        ctx.logger.error(f"❌ Erreur lors du traitement du texte: {e}")
        return f"Désolé, une erreur s'est produite lors du traitement de votre message. Veuillez réessayer."

async def generate_intent_response_text(ctx: Context, text: str, sender: str) -> str:
    """Génère une réponse texte pour une demande d'intent"""
    try:
        # Analyser le texte pour déterminer le type d'intent
        text_lower = text.lower()
        
        if any(word in text_lower for word in ["prix", "price", "condition"]):
            intent_type = "price_based"
        elif any(word in text_lower for word in ["temps", "time", "schedule", "dca"]):
            intent_type = "time_based"
        elif any(word in text_lower for word in ["risque", "risk", "stop", "protection"]):
            intent_type = "risk_management"
        else:
            intent_type = "general"
        
        # Créer une demande d'intent
        intent_request = IntentRequest(
            user_id=sender,
            intent_type=intent_type,
            parameters={"source": "chat_text", "original_message": text}
        )
        
        recommendation = await generate_intent_recommendation(ctx, intent_request)
        
        # Formater la réponse
        response = f"🎯 Recommandation d'intent basée sur votre message:\n\n"
        response += f"**Type**: {recommendation.get('type', 'N/A')}\n"
        if 'condition' in recommendation:
            response += f"**Condition**: {recommendation['condition']}\n"
        if 'action' in recommendation:
            response += f"**Action**: {recommendation['action']}\n"
        if 'confidence' in recommendation:
            response += f"**Confiance**: {recommendation['confidence']:.0%}\n"
        response += f"\n**Analyse**: {recommendation.get('reasoning', 'N/A')}"
        
        return response
        
    except Exception as e:
        ctx.logger.error(f"❌ Erreur génération intent: {e}")
        return "Désolé, je n'ai pas pu générer de recommandation d'intent pour le moment."

async def generate_trading_response_text(ctx: Context, text: str, sender: str) -> str:
    """Génère une réponse texte pour une demande de trading"""
    try:
        # Extraire le token du message
        text_upper = text.upper()
        tokens = ["ETH", "BTC", "USDC", "USDT", "BNB", "ADA", "SOL", "MATIC", "AVAX", "DOT", "LINK", "UNI", "ARB", "OP", "FLOW"]
        
        token_symbol = "ETH"  # par défaut
        for token in tokens:
            if token in text_upper:
                token_symbol = token
                break
        
        analysis = await send_trading_recommendation_to_simon(ctx, token_symbol)
        
        # Formater la réponse
        response = f"📊 Analyse trading pour {token_symbol}:\n\n"
        response += f"**Recommandation**: {analysis.get('recommendation', 'N/A').upper()}\n"
        response += f"**Confiance**: {analysis.get('confidence', 0):.0%}\n"
        if analysis.get('price_target'):
            response += f"**Objectif de prix**: ${analysis['price_target']:.4f}\n"
        if analysis.get('stop_loss'):
            response += f"**Stop loss**: ${analysis['stop_loss']:.4f}\n"
        response += f"**Sentiment**: {analysis.get('news_sentiment', 'N/A')}\n"
        response += f"\n**Analyse**: {analysis.get('reasoning', 'N/A')}"
        
        return response
        
    except Exception as e:
        ctx.logger.error(f"❌ Erreur analyse trading: {e}")
        return f"Désolé, je n'ai pas pu analyser {token_symbol} pour le moment."

def get_help_text() -> str:
    """Retourne le texte d'aide"""
    return """🤖 **IntentFi Agent - Commandes disponibles:**

📋 **Intents:**
• "Recommande-moi un intent pour ETH" 
• "Crée une stratégie DCA"
• "Intent de gestion des risques"

📊 **Trading:**
• "Analyse ETH" / "Trading ETH"
• "Acheter ou vendre BTC?"
• "Analyse de marché pour [TOKEN]"

💬 **Conversation:**
• Posez vos questions en langage naturel
• L'agent peut analyser et recommander

🚀 Tapez simplement votre question et je vous aiderai!"""

# Handlers pour compatibilité avec le protocole officiel uniquement


async def handle_chat_intent_request(ctx: Context, sender: str, msg: ChatMessage):
    """Processes an intent request via chat"""
    try:
        # Parser les métadonnées pour extraire les paramètres d'intent
        intent_data = msg.metadata
        
        if not intent_data:
            ctx.logger.warning("⚠️ Demande d'intent sans métadonnées")
            await send_chat_error(ctx, sender, msg.message_id, "Paramètres d'intent manquants")
            return
        
        # Créer une IntentRequest à partir des données du chat
        intent_request = IntentRequest(
            user_id=intent_data.get("user_id", sender),
            intent_type=intent_data.get("intent_type", "general"),
            parameters=intent_data.get("parameters", {})
        )
        
        ctx.logger.info(f"🎯 Traitement d'une demande d'intent via chat: {intent_request.intent_type}")
        
        # Générer la recommandation
        recommendation = await generate_intent_recommendation(ctx, intent_request)
        
        # Envoyer la réponse via chat
        response = ChatResponse(
            message_id=str(uuid.uuid4()),
            original_message_id=msg.message_id,
            sender_id=ctx.agent.address,
            recipient_id=sender,
            response_type=MessageType.INTENT_REQUEST,
            content=f"Recommandation d'intent générée: {recommendation.get('type', 'N/A')}",
            metadata={
                "recommendation": recommendation,
                "success": True
            },
            timestamp=datetime.now().isoformat()
        )
        
        await ctx.send(sender, response)
        ctx.logger.info(f"📤 Recommandation d'intent envoyée via chat à {sender}")
        
    except Exception as e:
        ctx.logger.error(f"❌ Erreur lors du traitement de l'intent via chat: {e}")
        await send_chat_error(ctx, sender, msg.message_id, f"Erreur: {str(e)}")


async def handle_chat_trading_request(ctx: Context, sender: str, msg: ChatMessage):
    """Processes a trading analysis request via chat"""
    try:
        # Parser les métadonnées pour extraire le token
        trading_data = msg.metadata
        token_symbol = trading_data.get("token_symbol", "ETH")
        
        ctx.logger.info(f"📊 Traitement d'une demande d'analyse trading via chat: {token_symbol}")
        
        # Générer l'analyse trading
        analysis = await send_trading_recommendation_to_simon(ctx, token_symbol)
        
        # Envoyer la réponse via chat
        response = ChatResponse(
            message_id=str(uuid.uuid4()),
            original_message_id=msg.message_id,
            sender_id=ctx.agent.address,
            recipient_id=sender,
            response_type=MessageType.TRADING_ANALYSIS,
            content=f"Analyse trading pour {token_symbol}: {analysis.get('recommendation', 'N/A')} (confiance: {analysis.get('confidence', 0):.0%})",
            metadata={
                "analysis": analysis,
                "token_symbol": token_symbol,
                "success": True
            },
            timestamp=datetime.now().isoformat()
        )
        
        await ctx.send(sender, response)
        ctx.logger.info(f"📤 Analyse trading envoyée via chat à {sender}")
        
    except Exception as e:
        ctx.logger.error(f"❌ Erreur lors de l'analyse trading via chat: {e}")
        await send_chat_error(ctx, sender, msg.message_id, f"Erreur: {str(e)}")


async def handle_chat_text_message(ctx: Context, sender: str, msg: ChatMessage):
    """Processes a simple text message via chat"""
    try:
        content_lower = msg.content.lower()
        
        # Détecter les intentions dans le message texte
        if any(word in content_lower for word in ["intent", "recommand", "stratégie", "conseil"]):
            # Rediriger vers le traitement d'intent
            await handle_chat_intent_from_text(ctx, sender, msg)
        elif any(word in content_lower for word in ["trading", "trade", "acheter", "vendre", "buy", "sell", "eth", "btc"]):
            # Rediriger vers l'analyse trading
            await handle_chat_trading_from_text(ctx, sender, msg)
        elif any(word in content_lower for word in ["aide", "help", "commands", "commandes"]):
            # Envoyer l'aide
            await send_chat_help(ctx, sender, msg.message_id)
        else:
            # Conversation générale - envoyer à Claude AI
            await handle_general_conversation(ctx, sender, msg)
            
    except Exception as e:
        ctx.logger.error(f"❌ Erreur lors du traitement du message texte: {e}")
        await send_chat_error(ctx, sender, msg.message_id, f"Erreur: {str(e)}")


async def handle_chat_intent_from_text(ctx: Context, sender: str, msg: ChatMessage):
    """Extracts an intent request from a text message"""
    # Analyser le texte pour déterminer le type d'intent
    content_lower = msg.content.lower()
    
    if any(word in content_lower for word in ["prix", "price", "condition"]):
        intent_type = "price_based"
    elif any(word in content_lower for word in ["temps", "time", "schedule", "dca"]):
        intent_type = "time_based"
    elif any(word in content_lower for word in ["risque", "risk", "stop", "protection"]):
        intent_type = "risk_management"
    else:
        intent_type = "general"
    
    # Créer une demande d'intent
    intent_request = IntentRequest(
        user_id=sender,
        intent_type=intent_type,
        parameters={"source": "chat_text", "original_message": msg.content}
    )
    
    recommendation = await generate_intent_recommendation(ctx, intent_request)
    
    # Formater la réponse de manière conversationnelle
    response_text = f"Basé sur votre message, voici ma recommandation d'intent:\n\n"
    response_text += f"🎯 Type: {recommendation.get('type', 'N/A')}\n"
    if 'condition' in recommendation:
        response_text += f"⚡ Condition: {recommendation['condition']}\n"
    if 'action' in recommendation:
        response_text += f"🚀 Action: {recommendation['action']}\n"
    if 'confidence' in recommendation:
        response_text += f"💪 Confiance: {recommendation['confidence']:.0%}\n"
    response_text += f"\n🧠 Raisonnement: {recommendation.get('reasoning', 'N/A')}"
    
    response = ChatResponse(
        message_id=str(uuid.uuid4()),
        original_message_id=msg.message_id,
        sender_id=ctx.agent.address,
        recipient_id=sender,
        response_type=MessageType.TEXT,
        content=response_text,
        metadata={"recommendation": recommendation},
        timestamp=datetime.now().isoformat()
    )
    
    await ctx.send(sender, response)


async def handle_chat_trading_from_text(ctx: Context, sender: str, msg: ChatMessage):
    """Extracts a trading request from a text message"""
    # Extraire le token du message
    content_upper = msg.content.upper()
    tokens = ["ETH", "BTC", "USDC", "USDT", "BNB", "ADA", "SOL", "MATIC", "AVAX", "DOT", "LINK", "UNI", "ARB", "OP", "FLOW"]
    
    token_symbol = "ETH"  # par défaut
    for token in tokens:
        if token in content_upper:
            token_symbol = token
            break
    
    analysis = await send_trading_recommendation_to_simon(ctx, token_symbol)
    
    # Formater la réponse de manière conversationnelle
    response_text = f"Voici mon analyse trading pour {token_symbol}:\n\n"
    response_text += f"📊 Recommandation: {analysis.get('recommendation', 'N/A').upper()}\n"
    response_text += f"💪 Confiance: {analysis.get('confidence', 0):.0%}\n"
    if analysis.get('price_target'):
        response_text += f"🎯 Objectif de prix: ${analysis['price_target']:.4f}\n"
    if analysis.get('stop_loss'):
        response_text += f"🛡️ Stop loss: ${analysis['stop_loss']:.4f}\n"
    response_text += f"📰 Sentiment: {analysis.get('news_sentiment', 'N/A')}\n"
    response_text += f"\n🧠 Analyse: {analysis.get('reasoning', 'N/A')}"
    
    response = ChatResponse(
        message_id=str(uuid.uuid4()),
        original_message_id=msg.message_id,
        sender_id=ctx.agent.address,
        recipient_id=sender,
        response_type=MessageType.TEXT,
        content=response_text,
        metadata={"analysis": analysis, "token_symbol": token_symbol},
        timestamp=datetime.now().isoformat()
    )
    
    await ctx.send(sender, response)


async def send_chat_help(ctx: Context, sender: str, original_message_id: str):
    """Sends help commands via chat"""
    help_text = """🤖 IntentFi Agent - Commandes disponibles:

📋 **Commandes d'Intent:**
• "Recommande-moi un intent pour ETH" 
• "Crée une stratégie DCA"
• "Intent de gestion des risques"

📊 **Commandes de Trading:**
• "Analyse ETH" / "Trading ETH"
• "Acheter ou vendre BTC?"
• "Analyse de marché pour [TOKEN]"

💬 **Conversation générale:**
• Posez vos questions en langage naturel
• L'agent peut analyser et recommander

🔧 **Formats supportés:**
• Messages texte naturels
• Demandes structurées avec métadonnées
• Commandes directes

Tapez simplement votre question et l'agent vous aidera! 🚀"""

    response = ChatResponse(
        message_id=str(uuid.uuid4()),
        original_message_id=original_message_id,
        sender_id=ctx.agent.address,
        recipient_id=sender,
        response_type=MessageType.SYSTEM_STATUS,
        content=help_text,
        metadata={"type": "help"},
        timestamp=datetime.now().isoformat()
    )
    
    await ctx.send(sender, response)


async def handle_general_conversation(ctx: Context, sender: str, msg: ChatMessage):
    """Processes general conversation using Claude AI"""
    try:
        # Créer un prompt conversationnel pour Claude
        conversation_prompt = f"""Tu es IntentFi Agent, un assistant IA spécialisé dans les stratégies d'investissement crypto et les intents financiers.

Message de l'utilisateur: "{msg.content}"

Réponds de manière conversationnelle et utile. Si la question concerne:
- Les crypto/trading: propose une analyse ou recommandation
- Les intents: explique les options disponibles  
- Autre: réponds naturellement en restant dans ton domaine d'expertise

Garde un ton amical et professionnel. Limite à 200 mots maximum."""

        # Envoyer à Claude AI
        request_id = str(uuid.uuid4())
        prompt = StructuredOutputPrompt(
            prompt=conversation_prompt,
            output_schema={
                "type": "object",
                "properties": {
                    "response": {"type": "string"},
                    "intent_suggestion": {"type": "string"},
                    "trading_suggestion": {"type": "string"}
                },
                "required": ["response"]
            }
        )
        
        # Stocker la demande pour traitement asynchrone
        pending_requests[request_id] = {
            "type": "chat_conversation",
            "sender": sender,
            "original_message_id": msg.message_id,
            "timestamp": datetime.now().isoformat()
        }
        
        try:
            await ctx.send(AI_AGENT_ADDRESS, prompt)
            ctx.logger.info(f"🧠 Conversation générale envoyée à Claude AI pour {sender}")
        except Exception as e:
            ctx.logger.error(f"❌ Erreur lors de l'envoi à Claude AI: {e}")
            # Envoyer directement une réponse par défaut en cas d'erreur
            fallback_response = ChatResponse(
                message_id=str(uuid.uuid4()),
                original_message_id=msg.message_id,
                sender_id=ctx.agent.address,
                recipient_id=sender,
                response_type=MessageType.TEXT,
                content="Je suis IntentFi Agent, votre assistant pour les stratégies crypto et les intents financiers. Comment puis-je vous aider avec vos investissements aujourd'hui? (Mode dégradé - Claude AI temporairement indisponible)",
                metadata={"type": "error_fallback"},
                timestamp=datetime.now().isoformat()
            )
            
            try:
                if CHAT_PROTOCOL_AVAILABLE:
                    # Utiliser le protocole officiel
                    chat_msg = ChatMessage(
                        msg_id=fallback_response.message_id,
                        content=[TextContent(text=fallback_response.content)]
                    )
                    await ctx.send(sender, chat_msg)
                else:
                    # Fallback custom
                    await ctx.send(sender, fallback_response)
                ctx.logger.info(f"📤 Réponse de fallback envoyée à {sender}")
            except Exception as e2:
                ctx.logger.error(f"❌ Erreur lors de l'envoi de la réponse de fallback: {e2}")
            
            # Nettoyer la demande pending
            if request_id in pending_requests:
                del pending_requests[request_id]
            return
        
        # Fallback si Claude ne répond pas dans les 10 secondes
        await asyncio.sleep(10)
        if request_id in pending_requests:
            # Claude n'a pas répondu, envoyer une réponse par défaut
            fallback_response = ChatResponse(
                message_id=str(uuid.uuid4()),
                original_message_id=msg.message_id,
                sender_id=ctx.agent.address,
                recipient_id=sender,
                response_type=MessageType.TEXT,
                content="Je suis IntentFi Agent, votre assistant pour les stratégies crypto et les intents financiers. Comment puis-je vous aider avec vos investissements aujourd'hui?",
                metadata={"type": "fallback"},
                timestamp=datetime.now().isoformat()
            )
            
            await ctx.send(sender, fallback_response)
            del pending_requests[request_id]
            
    except Exception as e:
        ctx.logger.error(f"❌ Erreur conversation générale: {e}")
        await send_chat_error(ctx, sender, msg.message_id, f"Erreur de conversation: {str(e)}")


async def send_chat_error(ctx: Context, sender: str, original_message_id: str, error_message: str):
    """Sends an error message via chat"""
    error_response = ChatResponse(
        message_id=str(uuid.uuid4()),
        original_message_id=original_message_id,
        sender_id=ctx.agent.address,
        recipient_id=sender,
        response_type=MessageType.ERROR,
        content=f"❌ Erreur: {error_message}",
        metadata={"error": True},
        timestamp=datetime.now().isoformat()
    )
    
    await ctx.send(sender, error_response)


@intentfi_protocol.on_message(model=IntentRequest)
async def handle_intent_request(ctx: Context, sender: str, msg: IntentRequest):
    """Processes intent requests and generates recommendations"""
    
    ctx.logger.info(f"📥 Nouvelle demande d'intent de {sender}")
    ctx.logger.info(f"User: {msg.user_id}, Type: {msg.intent_type}")
    
    # Générer une recommandation basée sur le type d'intent
    recommendation = await generate_intent_recommendation(ctx, msg)
    
    # Répondre avec la recommandation
    response = IntentResponse(
        success=True,
        recommendation=recommendation,
        message="Recommandation générée avec succès"
    )
    
    await ctx.send(sender, response)
    ctx.logger.info(f"📤 Recommandation envoyée à {sender}")

# Variables globales pour stocker les réponses de l'AI agent
pending_requests = {}
ai_responses = {}

class AIResponse(Model):
    request_id: str
    recommendation: dict[str, Any]

async def generate_intent_recommendation(ctx: Context, request: IntentRequest):
    """Generates an intent recommendation by actually contacting Claude AI agent"""
    
    # Créer un ID unique pour cette requête
    request_id = str(uuid.uuid4())
    
    # Créer un prompt financier spécialisé basé sur le type d'intent
    if request.intent_type == "price_based":
        financial_prompt = f"""
        Analysez les conditions de marché actuelles pour ETH et recommandez un intent de trading basé sur le prix.
        
        Contexte utilisateur:
        - User ID: {request.user_id}
        - Type d'intent: {request.intent_type}
        - Paramètres: {request.parameters}
        
        Analysez:
        1. Prix actuel ETH via Chainlink (récupérez le prix en temps réel)
        2. Sentiment du marché (bullish/bearish/neutral)
        3. Volatilité récente et tendances
        4. Niveaux de support/résistance techniques
        
        Recommandez un intent conditionnel avec:
        - Condition de prix précise basée sur l'analyse (ex: "ETH > $3200")
        - Action à exécuter (transfert cross-chain LayerZero, swap, etc.)
        - Niveau de confiance basé sur l'analyse (0-1)
        - Raisonnement détaillé avec données de marché
        
        IMPORTANT: Basez votre analyse sur des données réelles de marché.
        
        Répondez UNIQUEMENT au format JSON strict:
        {{
            "type": "conditional_transfer",
            "condition": "ETH > $XXXX",
            "action": "action détaillée avec LayerZero",
            "confidence": 0.XX,
            "reasoning": "analyse détaillée",
            "request_id": "{request_id}",
            "cross_chain_details": {{
                "source_chain": "Ethereum",
                "target_chain": "Optimism",
                "estimated_gas": "$X-Y USD"
            }}
        }}
        """
        
    elif request.intent_type == "time_based":
        financial_prompt = f"""
        Créez une stratégie d'investissement temporelle (DCA, scheduling) pour l'utilisateur.
        
        Contexte utilisateur:
        - User ID: {request.user_id}
        - Type d'intent: {request.intent_type}
        - Paramètres: {request.parameters}
        
        Analysez les tendances de marché actuelles et recommandez:
        1. Fréquence optimale d'investissement (quotidien/hebdomadaire/mensuel)
        2. Allocation recommandée basée sur la volatilité actuelle
        3. Stratégie cross-chain pour optimiser les coûts
        4. Montants adaptés au profil de risque
        
        Répondez UNIQUEMENT au format JSON strict:
        {{
            "type": "scheduled_dca",
            "schedule": "timing précis",
            "action": "action détaillée avec montants et chaînes",
            "confidence": 0.XX,
            "reasoning": "analyse de marché détaillée",
            "request_id": "{request_id}"
        }}
        """
        
    elif request.intent_type == "risk_management":
        financial_prompt = f"""
        Développez une stratégie de gestion des risques pour le portfolio de l'utilisateur.
        
        Contexte utilisateur:
        - User ID: {request.user_id}
        - Type d'intent: {request.intent_type}
        - Paramètres: {request.parameters}
        
        Analysez et recommandez:
        1. Niveaux de stop-loss basés sur la volatilité actuelle
        2. Diversification cross-chain avec LayerZero
        3. Stratégies de hedging adaptées au marché actuel
        4. Seuils de déclenchement optimaux
        
        Répondez UNIQUEMENT au format JSON strict:
        {{
            "type": "stop_loss_protection",
            "condition": "condition de déclenchement précise",
            "action": "action de protection détaillée",
            "confidence": 0.XX,
            "reasoning": "analyse de risque détaillée",
            "request_id": "{request_id}"
        }}
        """
        
    else:
        financial_prompt = f"""
        Analysez la demande d'intent personnalisée et proposez une stratégie financière adaptée.
        
        Contexte utilisateur:
        - User ID: {request.user_id}
        - Type d'intent: {request.intent_type}
        - Paramètres: {request.parameters}
        
        Fournissez une recommandation basée sur les conditions de marché actuelles.
        
        Répondez UNIQUEMENT au format JSON strict:
        {{
            "type": "custom_strategy",
            "reasoning": "analyse détaillée",
            "suggested_action": "action recommandée",
            "request_id": "{request_id}"
        }}
        """
    
    # Créer le schéma de réponse pour l'intent financier
    intent_schema = {
        "type": "object",
        "properties": {
            "type": {"type": "string"},
            "condition": {"type": "string"},
            "action": {"type": "string"},
            "confidence": {"type": "number", "minimum": 0, "maximum": 1},
            "reasoning": {"type": "string"},
            "request_id": {"type": "string"},
            "cross_chain_details": {
                "type": "object",
                "properties": {
                    "source_chain": {"type": "string"},
                    "target_chain": {"type": "string"},
                    "estimated_gas": {"type": "string"}
                }
            }
        },
        "required": ["type", "reasoning", "request_id"]
    }
    
    # Envoyer le prompt à l'AI agent Claude
    try:
        prompt = StructuredOutputPrompt(
            prompt=financial_prompt,
            output_schema=intent_schema
        )
        
        ctx.logger.info(f"🧠 Envoi du prompt financier à Claude AI pour {request.user_id}")
        ctx.logger.info(f"📤 Request ID: {request_id}")
        
        pending_requests[request_id] = {
            "user_id": request.user_id,
            "intent_type": request.intent_type,
            "timestamp": ctx.timestamp if hasattr(ctx, 'timestamp') else "N/A"
        }
        
        try:
            await ctx.send(AI_AGENT_ADDRESS, prompt)
            ctx.logger.info("✅ Prompt envoyé avec succès à Claude AI")
        except Exception as e:
            ctx.logger.error(f"❌ Erreur lors de l'envoi à Claude AI: {e}")
            # Nettoyer la demande pending et retourner une erreur
            if request_id in pending_requests:
                del pending_requests[request_id]
            return TradingAnalysisAPIResponse(
                success=False,
                message=f"Erreur de communication avec Claude AI: {str(e)}",
                timestamp=datetime.now().isoformat()
            )
        
        ctx.logger.info("⏳ En attente de la réponse de Claude AI (45s max avec retry)...")
        ctx.logger.info(f"🔍 Debug - AI_AGENT_ADDRESS: {AI_AGENT_ADDRESS}")
        
        import asyncio
        
        # Configuration retry avec backoff exponentiel
        max_retries = 3
        base_timeout = 15  # 15 secondes par tentative
        
        for retry_attempt in range(max_retries):
            current_timeout = base_timeout * (2 ** retry_attempt)  # 15s, 30s, 60s
            ctx.logger.info(f"🔄 Tentative {retry_attempt + 1}/{max_retries} - timeout: {current_timeout}s")
            
            # Attendre la réponse avec timeout étendu
            for attempt in range(current_timeout):
                await asyncio.sleep(1)
                
                if request_id in ai_responses:
                    ctx.logger.info(f"✅ Réponse reçue de Claude AI après {retry_attempt + 1} tentative(s)!")
                    response = ai_responses[request_id]
                    
                    # Nettoyer les variables
                    del ai_responses[request_id]
                    if request_id in pending_requests:
                        del pending_requests[request_id]
                    
                    return response
            
            # Si pas de réponse, retry (sauf dernière tentative)
            if retry_attempt < max_retries - 1:
                ctx.logger.warning(f"⏰ Timeout tentative {retry_attempt + 1} - retry dans 3s...")
                await asyncio.sleep(3)
                
                # Renvoyer la requête pour retry
                try:
                    await ctx.send(AI_AGENT_ADDRESS, prompt)
                    ctx.logger.info(f"🔄 Requête renvoyée (retry {retry_attempt + 2})")
                except Exception as retry_error:
                    ctx.logger.error(f"❌ Erreur lors du retry: {retry_error}")
        
        # Timeout final après tous les retries
        ctx.logger.warning("⏰ Timeout final - Claude AI ne répond pas après 3 tentatives, retour d'une recommandation par défaut")
        
        return {
            "type": "hold_position",
            "condition": "market_analysis_pending",
            "action": "Attendre une analyse de marché plus détaillée",
            "confidence": 0.3,
            "reasoning": "Timeout de l'analyse IA. Recommandation de prudence en attendant plus d'informations.",
            "request_id": request_id
        }
            
    except Exception as e:
        ctx.logger.error(f"❌ Erreur lors de l'envoi à Claude AI: {e}")
        return {
            "type": "error",
            "reasoning": f"Erreur lors de la communication avec Claude AI: {str(e)}",
            "suggested_action": "Réessayer la requête"
        }


@agent.on_rest_get("/health", HealthResponse)
async def health_check(ctx: Context) -> HealthResponse:
    """Health endpoint"""
    return HealthResponse(
        status="healthy",
        agent="IntentFi Recommender",
        address=agent.address,
        timestamp=datetime.now().isoformat()
    )


@agent.on_rest_post("/recommend", IntentRequest, IntentResponse)
async def recommend_intent(ctx: Context, req: IntentRequest) -> IntentResponse:
    """Endpoint to request an intent recommendation"""
    
    ctx.logger.info(f"🌐 API Call - Recommend Intent for user: {req.user_id}")
    
    try:
        recommendation = await generate_intent_recommendation(ctx, req)
        
        return IntentResponse(
            success=True,
            recommendation=recommendation,
            message="Recommandation générée via API REST"
        )
    except Exception as e:
        ctx.logger.error(f"Error during generation: {e}")
        return IntentResponse(
            success=False,
            recommendation={},
            message=f"Erreur: {str(e)}"
        )


@agent.on_rest_get("/intents/popular", PopularIntentsResponse)
async def get_popular_intents(ctx: Context) -> PopularIntentsResponse:
    """Endpoint to retrieve popular intents"""
    
    popular_intents = [
        {
            "name": "ETH Profit Taking",
            "condition": "ETH > $3000",
            "action": "Sell 25% ETH",
            "popularity": 0.78
        },
        {
            "name": "DCA Strategy", 
            "condition": "Weekly",
            "action": "Buy 20 USDC of ETH",
            "popularity": 0.85
        },
        {
            "name": "Cross-chain Arbitrage",
            "condition": "Price difference > 2%",
            "action": "Transfer to cheaper chain",
            "popularity": 0.65
        }
    ]
    
    return PopularIntentsResponse(
        popular_intents=popular_intents,
        total_count=len(popular_intents),
        timestamp=str(ctx.timestamp) if hasattr(ctx, 'timestamp') else "N/A"
    )


@agent.on_rest_get("/getJson", NewsJsonResponse)
async def get_news_json(ctx: Context) -> NewsJsonResponse:
    """Endpoint to retrieve news_logs.json file content"""
    
    ctx.logger.info("🌐 API Call - Retrieving news JSON")
    
    try:
        # Lire le fichier news_logs.json
        if not os.path.exists(NEWS_FILE):
            ctx.logger.warning(f"⚠️ File {NEWS_FILE} not found")
            return NewsJsonResponse(
                articles=[],
                total_articles=0,
                timestamp=datetime.now().isoformat(),
                status="no_data"
            )
        
        with open(NEWS_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        articles = data.get("articles", [])
        total_count = len(articles)
        
        ctx.logger.info(f"📰 JSON retrieved: {total_count} articles")
        
        return NewsJsonResponse(
            articles=articles,
            total_articles=total_count,
            timestamp=data.get("timestamp", datetime.now().isoformat()),
            status="success"
        )
        
    except json.JSONDecodeError as e:
        ctx.logger.error(f"❌ JSON Error: {e}")
        return NewsJsonResponse(
            articles=[],
            total_articles=0,
            timestamp=datetime.now().isoformat(),
            status="json_error"
        )
    except Exception as e:
        ctx.logger.error(f"❌ Reading error: {e}")
        return NewsJsonResponse(
            articles=[],
            total_articles=0,
            timestamp=datetime.now().isoformat(),
            status="error"
        )


@agent.on_rest_get("/getJsonDetails", NewsJsonDetailsResponse)
async def get_news_json_details(ctx: Context) -> NewsJsonDetailsResponse:
    """Endpoint pour récupérer le contenu du fichier news_logs.json avec analyse détaillée par Claude IA"""
    
    ctx.logger.info("🌐 API Call - Retrieving news JSON avec analyse détaillée")
    
    try:
        # Lire le fichier news_logs.json
        if not os.path.exists(NEWS_FILE):
            ctx.logger.warning(f"⚠️ File {NEWS_FILE} not found")
            return NewsJsonDetailsResponse(
                articles=[],
                total_articles=0,
                analyzed_articles=0,
                timestamp=datetime.now().isoformat(),
                status="no_data"
            )
        
        with open(NEWS_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        articles = data.get("articles", [])
        total_count = len(articles)
        
        ctx.logger.info(f"📰 JSON retrieved: {total_count} articles - Analyse en cours...")
        
        # Analyser chaque article avec Claude IA
        analyzed_articles = []
        analyzed_count = 0
        
        for i, article in enumerate(articles):
            ctx.logger.info(f"🔍 Analyse de l'article {i+1}/{total_count}")
            
            try:
                # Analyser l'article avec Claude IA
                analysis = await analyze_article_with_claude(ctx, article)
                
                # Créer une copie de l'article avec les nouveaux champs
                analyzed_article = article.copy()
                analyzed_article["review"] = analysis.get("review", "Analyse non disponible")
                analyzed_article["rate"] = analysis.get("rate", "neutral")
                
                analyzed_articles.append(analyzed_article)
                analyzed_count += 1
                
                ctx.logger.info(f"✅ Article {i+1} analysé - Rate: {analysis.get('rate', 'neutral')}")
                
                # Pause courte pour éviter le rate limiting
                await asyncio.sleep(1)
                
            except Exception as e:
                ctx.logger.error(f"❌ Erreur lors de l'analyse de l'article {i+1}: {e}")
                # Ajouter l'article sans analyse en cas d'erreur
                fallback_article = article.copy()
                fallback_article["review"] = f"Erreur lors de l'analyse: {str(e)}"
                fallback_article["rate"] = "neutral"
                analyzed_articles.append(fallback_article)
        
        ctx.logger.info(f"📊 Analyse terminée : {analyzed_count}/{total_count} articles analysés avec succès")
        
        return NewsJsonDetailsResponse(
            articles=analyzed_articles,
            total_articles=total_count,
            analyzed_articles=analyzed_count,
            timestamp=datetime.now().isoformat(),
            status="success"
        )
        
    except json.JSONDecodeError as e:
        ctx.logger.error(f"❌ JSON Error: {e}")
        return NewsJsonDetailsResponse(
            articles=[],
            total_articles=0,
            analyzed_articles=0,
            timestamp=datetime.now().isoformat(),
            status="json_error"
        )
    except Exception as e:
        ctx.logger.error(f"❌ Reading error: {e}")
        return NewsJsonDetailsResponse(
            articles=[],
            total_articles=0,
            analyzed_articles=0,
            timestamp=datetime.now().isoformat(),
            status="error"
        )


@agent.on_rest_get("/getAnalyzed", NewsJsonDetailsResponse)
async def get_news_analyzed(ctx: Context) -> NewsJsonDetailsResponse:
    """Endpoint pour récupérer les articles analysés depuis le fichier news_analyzed.json"""
    
    ctx.logger.info("🌐 API Call - Récupération des articles analysés")
    
    analyzed_file = "news_analyzed.json"
    
    try:
        # Vérifier si le fichier analysé existe
        if not os.path.exists(analyzed_file):
            ctx.logger.warning(f"⚠️ Fichier {analyzed_file} non trouvé - Création en cours...")
            # Créer le fichier analysé à partir du fichier original
            await create_analyzed_file(ctx)
        
        # Lire le fichier analysé
        with open(analyzed_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        articles = data.get("articles", [])
        total_count = len(articles)
        analyzed_count = sum(1 for article in articles if 'review' in article and 'rate' in article)
        
        ctx.logger.info(f"📰 Fichier analysé récupéré : {total_count} articles, {analyzed_count} analysés")
        
        return NewsJsonDetailsResponse(
            articles=articles,
            total_articles=total_count,
            analyzed_articles=analyzed_count,
            timestamp=data.get("timestamp", datetime.now().isoformat()),
            status="success"
        )
        
    except json.JSONDecodeError as e:
        ctx.logger.error(f"❌ JSON Error: {e}")
        return NewsJsonDetailsResponse(
            articles=[],
            total_articles=0,
            analyzed_articles=0,
            timestamp=datetime.now().isoformat(),
            status="json_error"
        )
    except Exception as e:
        ctx.logger.error(f"❌ Reading error: {e}")
        return NewsJsonDetailsResponse(
            articles=[],
            total_articles=0,
            analyzed_articles=0,
            timestamp=datetime.now().isoformat(),
            status="error"
        )


@agent.on_rest_post("/updateAnalyzed", EmptyRequest, NewsJsonDetailsResponse)
async def update_analyzed_file_endpoint(ctx: Context, req: EmptyRequest) -> NewsJsonDetailsResponse:
    """Endpoint pour mettre à jour le fichier news_analyzed.json avec les dernières analyses"""
    
    ctx.logger.info("🌐 API Call - Mise à jour du fichier analysé")
    
    try:
        result = await create_analyzed_file(ctx)
        return result
    except Exception as e:
        ctx.logger.error(f"❌ Erreur lors de la mise à jour : {e}")
        return NewsJsonDetailsResponse(
            articles=[],
            total_articles=0,
            analyzed_articles=0,
            timestamp=datetime.now().isoformat(),
            status="error"
        )


async def create_analyzed_file(ctx: Context) -> NewsJsonDetailsResponse:
    """Crée ou met à jour le fichier news_analyzed.json avec les analyses IA"""
    
    analyzed_file = "news_analyzed.json"
    
    try:
        # Lire le fichier original
        if not os.path.exists(NEWS_FILE):
            ctx.logger.warning(f"⚠️ File {NEWS_FILE} not found")
            return NewsJsonDetailsResponse(
                articles=[],
                total_articles=0,
                analyzed_articles=0,
                timestamp=datetime.now().isoformat(),
                status="no_source_data"
            )
        
        with open(NEWS_FILE, 'r', encoding='utf-8') as f:
            original_data = json.load(f)
        
        original_articles = original_data.get("articles", [])
        total_count = len(original_articles)
        
        ctx.logger.info(f"📰 Création du fichier analysé : {total_count} articles à analyser")
        
        # Vérifier si le fichier analysé existe déjà
        existing_analyzed = {}
        if os.path.exists(analyzed_file):
            try:
                with open(analyzed_file, 'r', encoding='utf-8') as f:
                    existing_data = json.load(f)
                    for article in existing_data.get("articles", []):
                        # Utiliser l'URL comme clé unique
                        if 'url' in article and 'review' in article:
                            existing_analyzed[article['url']] = {
                                'review': article['review'],
                                'rate': article['rate']
                            }
                ctx.logger.info(f"♻️ Réutilisation de {len(existing_analyzed)} analyses existantes")
            except Exception as e:
                ctx.logger.warning(f"⚠️ Erreur lecture fichier existant: {e}")
        
        # Analyser chaque article
        analyzed_articles = []
        analyzed_count = 0
        
        for i, article in enumerate(original_articles):
            ctx.logger.info(f"🔍 Traitement article {i+1}/{total_count}")
            
            # Créer une copie de l'article
            analyzed_article = article.copy()
            
            # Vérifier si l'analyse existe déjà
            article_url = article.get('url', '')
            if article_url in existing_analyzed:
                # Réutiliser l'analyse existante
                analysis = existing_analyzed[article_url]
                analyzed_article["review"] = analysis['review']
                analyzed_article["rate"] = analysis['rate']
                analyzed_count += 1
                ctx.logger.info(f"♻️ Article {i+1} - Analyse réutilisée")
            else:
                # Nouvelle analyse avec Claude IA
                try:
                    analysis = await analyze_article_with_claude(ctx, article)
                    analyzed_article["review"] = analysis.get("review", "Analyse non disponible")
                    analyzed_article["rate"] = analysis.get("rate", "neutral")
                    analyzed_count += 1
                    ctx.logger.info(f"✅ Article {i+1} - Nouvelle analyse: {analysis.get('rate', 'neutral')}")
                    
                    # Pause pour éviter le rate limiting
                    await asyncio.sleep(1)
                    
                except Exception as e:
                    ctx.logger.error(f"❌ Erreur analyse article {i+1}: {e}")
                    analyzed_article["review"] = f"Erreur lors de l'analyse: {str(e)}"
                    analyzed_article["rate"] = "neutral"
            
            analyzed_articles.append(analyzed_article)
        
        # Sauvegarder le fichier analysé
        analyzed_data = {
            "timestamp": datetime.now().isoformat(),
            "total_articles": total_count,
            "analyzed_articles": analyzed_count,
            "source_file": NEWS_FILE,
            "articles": analyzed_articles
        }
        
        with open(analyzed_file, 'w', encoding='utf-8') as f:
            json.dump(analyzed_data, f, ensure_ascii=False, indent=2)
        
        ctx.logger.info(f"💾 Fichier {analyzed_file} créé avec succès")
        ctx.logger.info(f"📊 Résultat : {analyzed_count}/{total_count} articles analysés")
        
        return NewsJsonDetailsResponse(
            articles=analyzed_articles,
            total_articles=total_count,
            analyzed_articles=analyzed_count,
            timestamp=analyzed_data["timestamp"],
            status="success"
        )
        
    except Exception as e:
        ctx.logger.error(f"❌ Erreur création fichier analysé: {e}")
        return NewsJsonDetailsResponse(
            articles=[],
            total_articles=0,
            analyzed_articles=0,
            timestamp=datetime.now().isoformat(),
            status="error"
        )


async def analyze_article_with_claude(ctx: Context, article: dict) -> dict:
    """Analyse un article avec Claude IA pour obtenir review et rate"""
    
    try:
        # Extraire les informations pertinentes de l'article
        title = article.get("title", "")
        description = article.get("description", "")
        content = article.get("content", "")
        url = article.get("url", "")
        source = article.get("source", {}).get("name", "") if isinstance(article.get("source", {}), dict) else str(article.get("source", ""))
        published_at = article.get("publishedAt", "") or article.get("timestamp", "")
        
        # Créer le prompt pour Claude IA
        analysis_prompt = f"""
Tu es un expert en analyse financière crypto. Analyse cet article d'actualité et détermine s'il présente une opportunité financière intéressante dans le domaine des cryptomonnaies.

ARTICLE À ANALYSER:
Titre: {title}
Description: {description}
Contenu: {content[:1000] if content else "Non disponible"}
Source: {source}
Date: {published_at}
URL: {url}

INSTRUCTIONS:
1. Analyse l'impact potentiel de cette actualité sur le marché des cryptomonnaies
2. Identifie les opportunités d'investissement ou de trading
3. Évalue le sentiment général (bullish/bearish/neutral)
4. Fournis une review détaillée et professionnelle

Concentre-toi sur:
- Impact sur les prix des crypto-monnaies
- Nouvelles technologies blockchain
- Réglementations crypto
- Adoptions institutionnelles
- Innovations DeFi/Web3
- Partenariats significatifs
- Tendances de marché

RÉPONDRE UNIQUEMENT au format JSON strict:
{{
    "review": "Analyse détaillée de l'opportunité financière crypto de cette actualité. Explique clairement pourquoi c'est intéressant ou non pour les investisseurs crypto, les impacts potentiels sur les prix, les tokens concernés, et les stratégies recommandées.",
    "rate": "bullish|bearish|neutral"
}}

IMPORTANT: 
- "bullish" = actualité positive pour le marché crypto, opportunité d'achat
- "bearish" = actualité négative pour le marché crypto, signal de vente/prudence  
- "neutral" = actualité sans impact significatif sur le marché crypto
"""

        # Créer le schéma de réponse
        analysis_schema = {
            "type": "object",
            "properties": {
                "review": {
                    "type": "string",
                    "description": "Analyse détaillée de l'opportunité financière crypto"
                },
                "rate": {
                    "type": "string",
                    "enum": ["bullish", "bearish", "neutral"],
                    "description": "Sentiment général de l'actualité"
                }
            },
            "required": ["review", "rate"]
        }
        
        # Créer un ID unique pour cette analyse
        request_id = str(uuid4())
        
        # Envoyer le prompt à Claude IA
        prompt = StructuredOutputPrompt(
            prompt=analysis_prompt,
            output_schema=analysis_schema
        )
        
        ctx.logger.info(f"🧠 Envoi de l'analyse d'article à Claude IA")
        
        # Stocker la demande pour traitement asynchrone
        pending_requests[request_id] = {
            "type": "article_analysis",
            "article_title": title[:50] + "..." if len(title) > 50 else title,
            "timestamp": datetime.now().isoformat()
        }
        
        try:
            await ctx.send(AI_AGENT_ADDRESS, prompt)
            ctx.logger.info("📤 Prompt d'analyse envoyé à Claude IA")
        except Exception as e:
            ctx.logger.error(f"❌ Erreur lors de l'envoi à Claude IA: {e}")
            # Nettoyer la demande pending et retourner une erreur
            if request_id in pending_requests:
                del pending_requests[request_id]
            return {
                "review": f"Erreur de communication avec Claude IA: {str(e)}",
                "rate": "neutral"
            }
        
        # Attendre la réponse avec timeout et retry
        max_wait = 30  # 30 secondes max par article
        for attempt in range(max_wait):
            await asyncio.sleep(1)
            
            # Chercher la réponse dans ai_responses avec une logique flexible
            response = None
            for resp_id, resp_data in list(ai_responses.items()):
                if isinstance(resp_data, dict) and "review" in resp_data and "rate" in resp_data:
                    response = resp_data
                    # Nettoyer la réponse utilisée
                    del ai_responses[resp_id]
                    break
            
            if response:
                ctx.logger.info(f"✅ Analyse reçue de Claude AI - Rate: {response.get('rate')}")
                
                # Nettoyer la demande pending
                if request_id in pending_requests:
                    del pending_requests[request_id]
                
                return response
        
        # Timeout - retourner une analyse par défaut
        ctx.logger.warning(f"⏰ Timeout pour l'analyse Claude AI après {max_wait}s")
        
        # Nettoyer la demande pending
        if request_id in pending_requests:
            del pending_requests[request_id]
        
        # Analyse basique par mots-clés en fallback
        fallback_analysis = analyze_article_keywords(title, description, content)
        
        return {
            "review": f"Analyse automatique (Claude IA indisponible): {fallback_analysis['review']}",
            "rate": fallback_analysis["rate"]
        }
        
    except Exception as e:
        ctx.logger.error(f"❌ Erreur lors de l'analyse d'article: {e}")
        return {
            "review": f"Erreur lors de l'analyse: {str(e)}",
            "rate": "neutral"
        }


def analyze_article_keywords(title: str, description: str, content: str) -> dict:
    """Analyse basique par mots-clés en fallback si Claude IA n'est pas disponible"""
    
    text = f"{title} {description} {content}".lower()
    
    # Mots-clés bullish
    bullish_keywords = [
        'adoption', 'partnership', 'bull', 'surge', 'pump', 'moon', 'breakthrough',
        'institutional', 'investment', 'fund', 'etf', 'approved', 'launch', 'integration',
        'upgrade', 'innovation', 'defi', 'nft', 'web3', 'blockchain', 'crypto',
        'bitcoin', 'ethereum', 'gains', 'profit', 'success', 'milestone'
    ]
    
    # Mots-clés bearish  
    bearish_keywords = [
        'crash', 'dump', 'bear', 'regulation', 'ban', 'hack', 'exploit', 'scam',
        'fraud', 'investigation', 'lawsuit', 'fine', 'penalty', 'shutdown',
        'decline', 'fall', 'drop', 'loss', 'risk', 'warning', 'concern'
    ]
    
    bullish_score = sum(1 for keyword in bullish_keywords if keyword in text)
    bearish_score = sum(1 for keyword in bearish_keywords if keyword in text)
    
    if bullish_score > bearish_score and bullish_score >= 2:
        rate = "bullish"
        review = f"Actualité positive identifiée ({bullish_score} indicateurs bullish). Potentiel d'impact positif sur le marché crypto."
    elif bearish_score > bullish_score and bearish_score >= 2:
        rate = "bearish"
        review = f"Actualité négative identifiée ({bearish_score} indicateurs bearish). Prudence recommandée pour les investissements crypto."
    else:
        rate = "neutral"
        review = "Actualité sans impact significatif identifié sur le marché crypto. Surveillance recommandée."
    
    return {"review": review, "rate": rate}


async def send_trading_recommendation_to_simon(ctx: Context, token_symbol: str) -> dict:
    """Envoie une demande d'analyse trading à Simon Agent et retourne l'analyse"""
    
    try:
        ctx.logger.info(f"📊 Demande d'analyse trading pour {token_symbol} à Simon Agent")
        
        # Créer la demande d'analyse
        analysis_request = TradingAnalysisRequest(
            token_symbol=token_symbol,
            news_context=[],  # Peut être enrichi avec des données du news.json
            request_id=str(uuid4()),
            timestamp=datetime.now().isoformat()
        )
        
        # Envoyer à Simon Agent
        try:
            await ctx.send(SIMON_AGENT_ADDRESS, analysis_request)
            ctx.logger.info(f"📤 Demande d'analyse envoyée à Simon Agent pour {token_symbol}")
            
            # Attendre la réponse (timeout de 15 secondes)
            for attempt in range(15):
                await asyncio.sleep(1)
                
                # Vérifier si on a reçu une réponse de Simon
                # (Cette logique peut être améliorée selon l'implémentation de Simon)
                # Pour l'instant, retourner une analyse simulée
                break
            
            # Retourner une analyse simulée pour le moment
            return generate_mock_trading_analysis(token_symbol)
            
        except Exception as e:
            ctx.logger.error(f"❌ Error sending to Simon Agent: {e}")
            return generate_mock_trading_analysis(token_symbol)
            
    except Exception as e:
        ctx.logger.error(f"❌ Trading analysis error: {e}")
        return generate_mock_trading_analysis(token_symbol)


def generate_mock_trading_analysis(token_symbol: str) -> dict:
    """Génère une analyse trading de base si Simon Agent n'est pas disponible"""
    
    recommendations = ["buy", "sell", "hold"]
    sentiments = ["positive", "negative", "neutral"]
    
    # Analyse basique selon le token
    if token_symbol.upper() in ["ETH", "ETHEREUM"]:
        recommendation = "buy"
        confidence = 0.75
        reasoning = "ETH montre une tendance haussière avec l'écosystème DeFi en croissance"
        sentiment = "positive"
        price_target = 3200.0
        stop_loss = 2800.0
    elif token_symbol.upper() in ["BTC", "BITCOIN"]:
        recommendation = "hold"
        confidence = 0.65
        reasoning = "BTC reste stable, attendre confirmation de la tendance"
        sentiment = "neutral"
        price_target = 45000.0
        stop_loss = 40000.0
    else:
        recommendation = random.choice(recommendations)
        confidence = random.uniform(0.5, 0.8)
        reasoning = f"Analyse technique pour {token_symbol} basée sur les indicateurs de marché"
        sentiment = random.choice(sentiments)
        price_target = None
        stop_loss = None
    
    return {
        "recommendation": recommendation,
        "confidence": confidence,
        "reasoning": reasoning,
        "news_sentiment": sentiment,
        "price_target": price_target,
        "stop_loss": stop_loss
    }


@agent.on_message(TextResponse)
async def handle_text_response(ctx: Context, sender: str, msg: TextResponse):
    """Traite les réponses texte de Claude AI"""
    ctx.logger.info(f"📥 Réponse texte IA de ...{sender[-8:]}: {msg.text}")
    
    # Vérifier si c'est une réponse au test de connectivité
    if "Connected" in msg.text or "connectivity test" in msg.text.lower():
        ctx.logger.info("✅ Test de connectivité réussi avec l'AI Agent!")
    elif "Hello" in msg.text or "test" in msg.text.lower():
        ctx.logger.info("✅ Communication établie avec l'AI Agent!")


@agent.on_message(StructuredOutputResponse)
async def handle_structured_response(ctx: Context, sender: str, msg: StructuredOutputResponse):
    """Traite les réponses structurées de Claude AI pour les recommandations d'intents et analyses d'articles"""
    ctx.logger.info(f"📥 Réponse Claude AI reçue de ...{sender[-8:]}:")
    ctx.logger.info(f"🔍 Données: {msg.output}")
    
    try:
        # Vérifier si c'est une réponse d'intent financier avec request_id
        if isinstance(msg.output, dict) and 'request_id' in msg.output:
            request_id = msg.output['request_id']
            ctx.logger.info(f"🎯 Réponse pour request_id: {request_id}")
            
            # Stocker la réponse pour qu'elle soit récupérée par generate_intent_recommendation
            ai_responses[request_id] = msg.output
            
            ctx.logger.info("💰 Recommandation d'intent financier stockée!")
            ctx.logger.info("=" * 60)
            
            recommendation = msg.output
            
            # Affichage détaillé de la recommandation
            ctx.logger.info(f"🎯 TYPE: {recommendation.get('type', 'N/A')}")
            
            if 'condition' in recommendation:
                ctx.logger.info(f"⚡ CONDITION: {recommendation['condition']}")
            
            if 'action' in recommendation:
                ctx.logger.info(f"🚀 ACTION: {recommendation['action']}")
            
            if 'confidence' in recommendation:
                confidence = recommendation['confidence']
                confidence_emoji = "🟢" if confidence > 0.8 else "🟡" if confidence > 0.6 else "🔴"
                ctx.logger.info(f"{confidence_emoji} CONFIANCE: {confidence:.1%}")
            
            if 'reasoning' in recommendation:
                ctx.logger.info(f"🧠 ANALYSE: {recommendation['reasoning']}")
            
            if 'cross_chain_details' in recommendation:
                details = recommendation['cross_chain_details']
                ctx.logger.info("🌐 DÉTAILS CROSS-CHAIN:")
                ctx.logger.info(f"   📤 Source: {details.get('source_chain', 'N/A')}")
                ctx.logger.info(f"   📥 Destination: {details.get('target_chain', 'N/A')}")
                ctx.logger.info(f"   ⛽ Gas estimé: {details.get('estimated_gas', 'N/A')}")
            
            ctx.logger.info("=" * 60)
            
        # Vérifier si c'est une réponse d'analyse d'article (avec review et rate)
        elif isinstance(msg.output, dict) and 'review' in msg.output and 'rate' in msg.output:
            ctx.logger.info("📰 Analyse d'article reçue de Claude AI!")
            ctx.logger.info("=" * 60)
            
            analysis = msg.output
            
            # Affichage détaillé de l'analyse
            rate_emoji = "📈" if analysis.get('rate') == 'bullish' else "📉" if analysis.get('rate') == 'bearish' else "➡️"
            ctx.logger.info(f"{rate_emoji} SENTIMENT: {analysis.get('rate', 'N/A').upper()}")
            ctx.logger.info(f"📝 REVIEW: {analysis.get('review', 'N/A')[:200]}...")
            
            # Stocker la réponse dans ai_responses pour qu'elle soit récupérée par analyze_article_with_claude
            # Utiliser une clé générique car on ne peut pas prédire le request_id exact
            ai_responses[f"article_analysis_{datetime.now().timestamp()}"] = analysis
            
            ctx.logger.info("=" * 60)
            
        # Vérifier si c'est une réponse d'intent financier sans request_id (format général)
        elif isinstance(msg.output, dict) and any(key in msg.output for key in ['type', 'condition', 'action', 'reasoning']):
            ctx.logger.info("💰 Recommandation d'intent financier reçue (sans request_id)!")
            ctx.logger.info("=" * 60)
            
            recommendation = msg.output
            
            # Affichage détaillé
            ctx.logger.info(f"🎯 TYPE: {recommendation.get('type', 'N/A')}")
            
            if 'condition' in recommendation:
                ctx.logger.info(f"⚡ CONDITION: {recommendation['condition']}")
            
            if 'action' in recommendation:
                ctx.logger.info(f"🚀 ACTION: {recommendation['action']}")
            
            if 'confidence' in recommendation:
                confidence = recommendation['confidence']
                confidence_emoji = "🟢" if confidence > 0.8 else "🟡" if confidence > 0.6 else "🔴"
                ctx.logger.info(f"{confidence_emoji} CONFIANCE: {confidence:.1%}")
            
            if 'reasoning' in recommendation:
                ctx.logger.info(f"🧠 ANALYSE: {recommendation['reasoning']}")
        
        else:
            ctx.logger.info("⚠️ Format de réponse non reconnu:")
            ctx.logger.info(f"📄 Données: {msg.output}")
            
    except Exception as e:
        ctx.logger.error(f"❌ Erreur lors du traitement de la réponse structurée: {e}")

# Inclure les protocoles dans l'agent
agent.include(intentfi_protocol)
agent.include(simon_protocol)

# Inclusion conditionnelle du protocole de chat
if CHAT_PROTOCOL_AVAILABLE:
    try:
        agent.include(chat_protocol)
        print("✅ Protocole de chat officiel inclus")
    except Exception as e:
        print(f"⚠️ Impossible d'inclure le protocole de chat officiel: {e}")
        print("   Utilisation du protocole custom ASI_ONE_Chat")
        # Créer un protocole custom en fallback
        custom_chat = Protocol("ASI_ONE_Chat")
        agent.include(custom_chat)
else:
    agent.include(chat_protocol)

# Point d'entrée principal
if __name__ == "__main__":
    print("🚀 Démarrage de l'agent IntentFi...")
    print(f"🆔 Agent ID: {agent.address}")
    print(f"🌐 Endpoint: http://localhost:8001")
    print("📡 Endpoints API disponibles:")
    print("   - GET /health - Statut de l'agent")
    print("   - GET /getJson - Articles de news bruts")
    print("   - GET /getJsonDetails - Articles analysés avec Claude IA")
    print("   - GET /getAnalyzed - Articles du cache (performance)")
    print("   - POST /updateAnalyzed - Mettre à jour le cache")
    print("   - GET /asi-one/metadata - Métadonnées ASI ONE")
    print("   - GET /popular-intents - Intents populaires")
    print("   - POST /recommend/intent - Recommandation d'intent")
    print("   - POST /trading/recommend - Recommandation trading")
    print("   - POST /chat/send - Chat avec l'agent")
    print("   - GET /chat/conversations - Liste des conversations")
    print("   - GET /chat/analytics - Analytiques de chat")
    print("")
    print("🔗 Protocoles inclus:")
    print("   - IntentFi (recommandations d'intents)")
    print("   - IntelleC Communication (communication avec Simon)")
    if CHAT_PROTOCOL_AVAILABLE:
        print("   - Chat Protocol (protocole officiel Fetch.ai)")
    else:
        print("   - ASI_ONE_Chat (protocole custom)")
    print("")
    print("💡 Utilisation:")
    print("   - Lancer news.py en parallèle pour alimenter les actualités")
    print("   - Tester les endpoints avec curl ou un client HTTP")
    print("   - Intégrer avec ASI ONE pour les conversations")
    print("")
    print("🏃‍♂️ Lancement de l'agent...")
    
    try:
        agent.run()
    except KeyboardInterrupt:
        print("\n🛑 Arrêt de l'agent IntentFi")
    except Exception as e:
        print(f"\n❌ Erreur lors du lancement: {e}")
        raise e