#!/bin/bash
# Guide de lancement des agents IntentFi

echo "🚀 Guide de lancement des agents IntentFi"
echo "========================================"
echo ""
echo "Ouvrez 2 terminaux et exécutez :"
echo ""
echo "📊 Terminal 1 - IntentFi Agent (port 8000):"
echo "cd /Users/matteo/ETHGlobalCannes/agents/intellect"
echo "/usr/local/opt/python@3.11/bin/python3.11 intellect.py"
echo ""
echo "📰 Terminal 2 - News Agent (port 8001):"
echo "cd /Users/matteo/ETHGlobalCannes/agents/intellect" 
echo "/usr/local/opt/python@3.11/bin/python3.11 news.py"
echo ""
echo "🔗 URLs disponibles :"
echo "• IntentFi: http://localhost:8000"
echo "• News: http://localhost:8001"
echo ""
echo "🧪 Test rapide :"
echo "curl http://localhost:8000/health"
echo "curl http://localhost:8001/health"
echo ""
echo "✨ Alternatives :"
echo "python3 news_launcher.py  # News seul avec logs temps réel + JSON"
